### ISSUE TITLE
Postgres Example

### ISSUE THREAD

**Issue by Fyb3roptik** [DATA-DOG/go-txdb#16]
I have tried everything and for the life of me I cannot get Postgres to work. Can I get an example for connecting using postgres?

Thanks!

**Comment by l3pp4rd** [comment]
Hi, the postgres sql driver is also tested in txdb tests. That should be enough as an example. Just check the test.go files.

**Comment by Fyb3roptik** [comment]
The issue for me was I am using go-pg and it does not use the sql.DB driver and instead uses its own. I might have a go at trying to integrate support for it here

**Comment by l3pp4rd** [comment]
well, txdb is only compatible with standard go sql library.
