### ISSUE TITLE
Auto increment values does not reset completely

### ISSUE THREAD

**Issue by qburst-ambareeshb** [DATA-DOG/go-txdb#23]
When running tests though auto increment values get cleared after closing the db connection, next time the value of auto increment field is the continuation of the previous one.

this issue is found in ` postgres:9.6.11-alpine `

**Comment by l3pp4rd** [comment]
well, txdb cannot change the behavior of the sql database, that is up to the driver. all you can do is just do not depend on these incremented keys.
