### ISSUE TITLE
Breaks go's sql driver semantics

### ISSUE THREAD

**Issue by bouk** [DATA-DOG/go-txdb#27]
https://golang.org/pkg/database/sql/driver/#Driver says that Open's returned connection is only used by one goroutine at a time, but because the txdb Driver returns the same connection multiple times, you can end up in a situation where the same connection is used in multiple concurrent threads of execution.

The only correct thing to do is to return an error/panic if another connection is opened while the connection is already being used. It points to a programming error, for example an sql.Rows not being closed, or the *sql.DB being used while a transaction has started.

**Comment by l3pp4rd** [comment]
Hi, txdb has composite behavior when opening, it will always return same connection if DSN is the same. Change DSN if you want a separate transaction opened.

**Comment by l3pp4rd** [comment]
Currently all the tests in this package changes dsn for each test in order to run them concurrently

**Comment by l3pp4rd** [comment]
I do not care if it breaks the contract, it allows to isolate even production code to run within transaction no matter how many times connection is reopened if dsn is the same. I have created this package for people to efficiently test their code in fuctional or integration tests

**Comment by bouk** [comment]
Thanks for explaining!
