### ISSUE TITLE
savepoint "tx_17" does not exist

### ISSUE THREAD

**Issue by samsondav** [DATA-DOG/go-txdb#31]
I get this error running my test suite.

It can occur in different tests but it is _always_ `tx_17`.

Is there some hardcoded limit for 16 savepoints somewhere?

**Comment by l3pp4rd** [comment]
Very likely it is the default database configuration limit. Check the db you are using

**Comment by l3pp4rd** [comment]
Also note, if you use the same DSN in every test to open tx-db and you do not close the database you opened, then you all of your tests may run within the same transaction. You should close the txdb on every test, in order to rollback the transaction
