### ISSUE TITLE
ALTER TABLE table_name AUTO_INCREMENT does not rollback inserted entry

### ISSUE THREAD

**Issue by bhavyata9** [DATA-DOG/go-txdb#32]
Hi,

We have a test that executes`ALTER TABLE table_name AUTO_INCREMENT =  2`, and then inserts a row in `table_name`. However, we find that the inserted row is still in the `table_name` after the test is done. If we don't do the alter, then the entry gets deleted, but ofcourse, the ids are incremented. 

We are using mysql.

**Comment by l3pp4rd** [comment]
Mysql does not support rolling back alter table. Read the api docs in mysql
