### ISSUE TITLE
txDriver.realConn is not closed.

### ISSUE THREAD

**Issue by KoichiWada** [DATA-DOG/go-txdb#35]
In this commit, txDriver.realConn holds a new connection, but it's not closed anywhere.

https://github.com/DATA-DOG/go-txdb/pull/34/commits/c0f89b56ce7b989e36f726f6b97617e5f37ededf

We got `Too many connections` in our tests with the latest go-txdb.

**Comment by l3pp4rd** [comment]
Hi, can you submit a PR this was recently introduced, very busy these days
