### ISSUE TITLE
Consider supporting the sql.Connector interface

### ISSUE THREAD

**Issue by flimzy** [DATA-DOG/go-txdb#40]
If this package were to satisfy the [driver.Connector](https://golang.org/pkg/database/sql/driver/#Connector) interface, it would no longer be necessary to register a driver for every new instance, which could make certain test patterns much simpler.

I'd be happy to submit a PR if it's likely to be accepted.

**Comment by l3pp4rd** [comment]
Hi, that would be very welcome, thanks!

**Comment by lopezator** [comment]
Hey! This is the new way to write sql drivers, and I need I would need this to wrap txdb inside my own wrapper (adding retrial functionality, for example).

See:

https://pkg.go.dev/database/sql/driver

> The driver interface has evolved over time. Drivers should implement Connector and DriverContext interfaces.

Any reason why #41 development stopped? Can we recover it somehow?
