### ISSUE TITLE
Ping ends up in error

### ISSUE THREAD

**Issue by sagikazarmark** [DATA-DOG/go-txdb#5]
When trying to Ping the database to check if there is a connection I receive the following error:

https://pastebin.com/6bnAztAk

Looks like `Ping` calls itself recursively: https://github.com/DATA-DOG/go-txdb/blob/master/db_go18.go#L96-L98

At least it could return with nil, even if it is not implemented for the moment.

**Comment by l3pp4rd** [comment]
should be resolved, thanks for reporting ;)

**Comment by sagikazarmark** [comment]
Awesome, thanks for the prompt fix
