### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by l3pp4rd** [DATA-DOG/go-txdb#50]
Hi, I do not have much spare time for this library and haven't used go over few years. Open up a conversation if you are using this library and willing to maintain it for some time. I'll give the permission to manage repository.

**Comment by Yiling-J** [comment]
Hi @l3pp4rd , I can help maintain this library. I'm the author of [Theine](https://github.com/Yiling-J/theine-go) and use Go a lot. Though I don't use [go-txdb](https://github.com/DATA-DOG/go-txdb) much, after taking a look the repo I think the code is not very complicated and I can help

**Comment by stefafafan** [comment]
Hello @l3pp4rd , I am also willing to help if you like. I use go-txdb for my job product (sorry it is closed source), so I am motivated to keep this library up to date.

**Comment by Yiling-J** [comment]
@stefafafan I just creating a PR and do some refactors, would you like to take a look? https://github.com/DATA-DOG/go-txdb/pull/51

**Comment by stefafafan** [comment]
@Yiling-J Thanks, I'm not a collaborator yet but I will take a look at it.

**Comment by stefafafan** [comment]
@Yiling-J Yes, I am a collaborator now. Yeah, I will try taking a look at that.

**Comment by jsteenb2** [comment]
Hi there, I'd also offer up time to maintain the project. We utilize this a lot at our company.

**Comment by flimzy** [comment]
If it's still relevant, I'm happy to throw my hat in the ring to help with maintainership. While I've not contributed to this project, other than an unmerged PR, I still hope can get some attention, I've been a heavy user of this package in the past, and will continue to do so in the future, so I have a vested interest in keeping it in tip-top shape.  I'm also the (co-)maintainer of two other Go repositories, so adding one to my normal routine would be easy.

**Comment by flimzy** [comment]
I think we've got maintenance under control at this stage. If you feel otherwise, @l3pp4rd, feel free to reopen.
