### ISSUE TITLE
retry on failure

### ISSUE THREAD

**Issue by lopezator** [DATA-DOG/go-txdb#60]
Hello!

We are using `txdb` along with `cockroachdb` for integration testing (using `pgx` driver) and it's working fine.

The thing is that sometimes, `CockroachDB` can throw some errors that need to be retried, and for that purpose there is this driver:

https://github.com/cockroachdb/cockroach-go

The question is... any idea or anyone built a logic around retrial with txdb? It doesn't have to be with cockroachdb or anything, I just would need some guidance if someone has any idea on what should I do if the engine errs:

ROLLBACK, BEGIN again (with `txdb_1` SAVEPOINT or something) and retry?

Any ideas would be welcome, thank you! :pray: 

CC/ @l3pp4rd @Yiling-J @flimzy

**Comment by Yiling-J** [comment]
from cockroach-go code, you need to provide a `*sql.DB` when calling `ExecuteTx`. How about create a sql.DB with `db := sql.OpenDB(txdb.New("mysql", "root@/txdb_test"))` and use that in `ExecuteTx`?

**Comment by lopezator** [comment]
Hey @Yiling-J yep, but I obviously didn't wanted to add that method to every database call I make in my codebase, so what I thought was to add a new driver wrapping `pgx` and `QueryContext` and `ExecContext` methods, adding that retrial logic, and I went up with:

https://github.com/lopezator/crdbx

But I end up with:

txdb -> crdbx -> pgx

And things get a bit out of my control, with errs like:

```
sql: transaction has already been committed or rolled back
```

**Comment by lopezator** [comment]
Thanks a bunch for your answer btw @Yiling-J ! :)

**Comment by Yiling-J** [comment]
@lopezator is this possible with crdbx? Or you already tried and still getting `sql: transaction has already been committed or rolled back` error?
```go
func main() {
    crdbxDriver := crdbx.NewDriver(....)
    sql.Register("crdbx", crdbxDriver)
    txdb.Register("txdb", "crdbx", "root@/txdb_test")
    ....
}
```

**Comment by lopezator** [comment]
> @lopezator is this possible with crdbx? Or you already tried and still getting `sql: transaction has already been committed or rolled back` error?
> 
> ```go
> func main() {
>     crdbxDriver := crdbx.NewDriver(....)
>     sql.Register("crdbx", crdbxDriver)
>     txdb.Register("txdb", "crdbx", "root@/txdb_test")
>     ....
> }
> ```

Yes, that works most of the time and works great for the errs `cockroach-go` handles like:

`CR000` and `40001`.

But because of race conditions (I guess) sometimes I get some `25P02` as well.

+info: https://postgrespro.com/list/thread-id/2472281

So I wanted to handle those as well, something like this:

```go
for {
	  if err := crdb.Execute(func() error {
		    var err error
		    rows, err = querier.QueryContext(ctx, query, args)
		    return err
	  }); err != nil {
	  if errCode(err) != "25P02" {
		  // restart transaction here, c.Close()? 
		  continue
	  }
	  return nil, err
}
```

But I am not able to restart the txdb transaction from inside the if in crdbx to retry.

Thanks a lot @Yiling-J !!

**Comment by Yiling-J** [comment]
@lopezator what happens when running the code without manually restart transaction? BTW should be `if errCode(err) == "25P02"` if i understand correctly? I think from crdb's doc Execute is used to run a single statement so no manually restart needed. If you use `ExecuteTx` maybe rollback to `savepoint cockroach_restart` is necessary

**Comment by lopezator** [comment]
> @lopezator what happens when running the code without manually restart transaction? BTW should be if errCode(err) == "25P02" if i understand correctly? I think from crdb's doc Execute is used to run a single statement so no manually restart needed.

Yes! You are right! it is a `==` 25P02. I am using `Execute` with individual statements. I tried `ROLLBACK`, `ABORT` (these interfere with txdb), and also `ROLLBACK TO SAVEPOINT cockroach_restart`. 

The thing is that once the first race of `25P02` appear (sometimes appears, sometimes not) I am not able to recover from that :disappointed: . Any retry, abort, rollback... even with backoffs gives unexpected results or the same 25P02 over and over again. 

Maybe is something just from cockroach, not sure.

Thanks again for trying to help. If you are ran our of ideas maybe you can close this! 

Best.

**Comment by lopezator** [comment]
> I think if you are using Execute method with a single statement, because the statement itself is atomic, you don't need to rollback manually, just run that statement again.

Yep, that's what I am doing, but not sure why in the specific case of 25P02, retrying is not helping, not sure where exactly is the problem TBH.

**Comment by Yiling-J** [comment]
@lopezator seems a cockroachdb/postgresql issue? TBH I have no idea how to reproduce or fix this. I think i can close it for now. txdb is not that fancy, it's just a wrapper of your existing driver, so if you find a way to solve this, a PR is always welcome

**Comment by lopezator** [comment]
Sure! Thanks a lot for your willingness to help @Yiling-J . It greatly appreciated.
