### ISSUE TITLE
How to use with pgxpool?

### ISSUE THREAD

**Issue by hotrush** [DATA-DOG/go-txdb#68]
Any hint much appreciated

**Comment by flimzy** [comment]
go-txdb only works with `database/sql` drivers. pgxpool does not use this interface. pgx does provide a compatibility layer for `database/sql`, but as far as I'm aware, that's completely independent from pgxpool, since `database/sql` handles its own pool.

**Comment by peterldowns** [comment]
@hotrush you might want to take a look at [my project pgtestdb](https://github.com/peterldowns/pgtestdb) — the `pgtestdb.Custom()` method will let you create a new test database, then connect to it with pgxpool.

**Comment by hotrush** [comment]
@peterldowns thanks for the hint, already switched to it. Much better than txdb 👍
